### ISSUE TITLE
AMP Review 1

### ISSUE THREAD

**Issue by melaniebeck** [fastforwardlabs/airline_delay_prediction#1]
- [x] 1. Minor suggestions for the `.yaml`
  - [x] a. Does it make sense to update the name of the prototype to align more closely with the project name? Something like "Airline Delay Prediction Demo" instead of "Flight Demo"? https://github.com/fastforwardlabs/airline_delay_prediction/blob/487450b9e1837b90cf7b126bd5e78ac930dbd476/.project-metadata.yaml#L1
  - [x] b. reference to the Telco Churn model should probably be updated to reflect the current project https://github.com/fastforwardlabs/airline_delay_prediction/blob/487450b9e1837b90cf7b126bd5e78ac930dbd476/.project-metadata.yaml#L130 https://github.com/fastforwardlabs/airline_delay_prediction/blob/487450b9e1837b90cf7b126bd5e78ac930dbd476/.project-metadata.yaml#L139
- [x] 2. Add Cloudera copyright source footer to the [data processing notebook](https://github.com/fastforwardlabs/airline_delay_prediction/blob/master/code/2_data_analysis.ipynb)
- [x] 3. Update reference to Telco Churn model in the code documentation, if appropriate https://github.com/fastforwardlabs/airline_delay_prediction/blob/487450b9e1837b90cf7b126bd5e78ac930dbd476/code/0_bootstrap.py#L44
- [x] 4. I don't understand how one should use the Cancelled Flight Prediction interface. I tried entering in different flight information but it always says "Not Cancelled" so *I can't tell if it's actually working or if there's a bug*.  Additionally, having to enter such detailed information about a given flight is not very user-friendly.   Ideas to mitigate these issues: 
   - [x] a. Option 1: Is there a way to make it easier for users to enter flight information? Say, not having to enter so many fields like distance, flight duration, hour, week (how are people supposed to know what format to enter "hour" and "week" as?). Most people don't know this kind of information about a flight making the app impractical. Is the model actually using all of those fields for its prediction? It would be nice to simplify it such that it takes in carrier, arrival and departure locations, and departure time, for example. Or at least provide the user with another set of flight information that they can enter which would yield a "Cancelled" prediction so they can see the model in action. 
   - [ ] b.  Option 2: If it's too much to simplify the app, then perhaps we could have more boilerplate about what a user should expect to gain from it. For example, if it's not really meant to be interacted with, we could say as much and add that it is there purely to demonstrate CML Applications or Model Endpoints or something similar. 
- [x] 5. Thumbnail for Catalog page -- same as the one in the repo or something different?

**Comment by andrewrreed** [comment]
Thanks for the feedback, Melanie!

I've incorporated all of the suggested changes including updating the UI to:

- Remove several of the impractical features
- Add searchable dropdowns for each field so users aren't guessing at values
- Add the prediction confidence along with the predicted class so users can visually see the app "working" each time they click the button

I also changed the name of the project because it dawned on me that we are actually predicting flight cancellations, not delays 😄  

Let me know if there are any further improvements you can spot, thanks!

**Comment by melaniebeck** [comment]
Looks amazing, Andrew! Fantastic improvements. I give this AMP my Seal of Approval. :)
